backstage/urls.py

from django.urls import path, include, re_path

from backstage import views

app_name = 'backstage'

category_patterns = [
    path('', views.category, name="category"),
    path('page/<int:page>/', views.category, name="category_pages"),
    path('create/', views.create_category, name="create_new_category"),
    path('delete/<int:category_id>/', views.delete_category, name="delete_category"),
]

edit_patterns = [
    path('', views.edit_article, name="edit"),
    re_path("(?P<new>(new|edited))/", views.edit_article, name="edit_article"),
    path('save/', views.save_article, name="save_article"),
    path('publish/', views.pub_article, name="publish_article"),
    path('load/', views.load_markdown, name="load_markdown"),
    path('full-editor/', views.edit_article, kwargs={'is_full': True}, name="full_editor")
]

articles_patterns = [
    path('all/', views.all_articles, name="all_articles"),
    path('all/page/<int:page>/', views.all_articles, name="all_articles_pages"),
    path('all/e/<int:article_id>/', views.to_edit, name="to_edit_from_all"),
    path('all/d/', views.to_delete, name="to_delete_from_all"),
    path('published/', views.published_articles, name="published_articles"),
    path('published/page/<int:page>/', views.published_articles, name="pub_articles_pages"),
    path('published/e/<int:article_id>/', views.to_edit, name="to_edit_from_pub"),
    path('published/d/', views.cancel_publish, name="to_delete_from_pub"),
    path('revert/', views.revert_from_trash, name="revert_from_trash"),
    path('delPermanently/', views.delete_permanently, name="delete_permanently"),
]

statistics_patterns = [
    path('', views.statistics, name="statistics"),
    path('sys/', views.sys, name="get_system_info"),
    path('nav/', views.nav_info, name="get_nav_info"),
    path('location/', views.get_visitors_location_info, name='get_location_info'),
    path('pv/<int:option>/', views.get_pv_info, name="get_pv_info")
]

upload_patterns = [
    path('image/', views.image_upload, name="image_upload"),
]

message_box_patterns = [
    path('', views.message_box, name="message_box"),
    path('p/<int:p>/', views.message_box, name="message_pages"),
    path('read/<int:message_id>/', views.read_message, name="read_message"),
    path('delete/', views.delete_message, name="delete_message"),
    path('stat/', views.change_stat, name="change_state"),
]

urlpatterns = [
    path('', views.statistics, name="index"),
    path('login/', views.login, name='login'),
    path('login_validate/', views.login_validate, name='validate'),
    path('logout/', views.logout, name='logout'),
    path('statistics/', include(statistics_patterns)),
    path('category/', include(category_patterns)),
    path('edit/', include(edit_patterns)),
    path('articles/', include(articles_patterns)),
    re_path("(?P<dt>(draft|trash))/(?P<p>\d*)/", views.draft_and_trash, name="draft_and_trash"),
    path('upload/', include(upload_patterns)),
    path('message/', include(message_box_patterns))
]


blog/urls.py
from django.urls import path, include
from blog import views

app_name = 'blog'

details_patterns = [
    path('<int:p>/', views.get_all_puba, name="get_all_published_articles"),
    path('details/<int:pub_id>', views.get_detail, name="published_article_detail"),
    path('praise/', views.praise, name="praise"),
    path('comment/', views.to_comment, name="comment"),
    path('load_comments/', views.load_comments, name="load_comments")
]

side_info_patterns = [
    path('latest/', views.get_latest_articles, name="get_latest_articles"),
    path('popular/', views.get_popular_articles, name="get_popular_articles"),
    path('categories/', views.get_categories, name="get_categories")
]

categories_patterns = [
    path('<int:c>/', views.category_view, name="category_view"),
    path('<int:c>/p/<int:p>/', views.category_view, name="category_view_pages")
]

message_patterns = [
    path('', views.message, name="leaving message"),
    path('compose/', views.compose, name="compose message")
]

urlpatterns = [
    path('', views.get_all_puba, name="blog_index", kwargs={'p': 1}),
    path('a/', include(details_patterns)),
    path('side/', include(side_info_patterns)),
    path('categories/', include(categories_patterns)),
    path('message/', include(message_patterns))
]

ip/urls.py
from django.urls import path
from ip import views


app_name = 'ip'

urlpatterns = [
    path('', views.ip_query, name='ip_query'),
    path('query/', views.do_ip_query, name='do_ip_query'),
]

one/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='blog/')),
    path('back/', include('backstage.urls')),
    path('captcha/', include('captcha.urls')),
    path('blog/', include('blog.urls')),
    path('ip/', include('ip.urls')),
    path('favicon.ico', RedirectView.as_view(url='static/favicon.ico'))
]

handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.page_error

backstage/models/article_models.py
from django.db import models


class PublishedArticle(models.Model):

    pub_id = models.IntegerField(unique=True)
    article = models.OneToOneField('Article', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.SET_DEFAULT, default=1,
                                 related_name='published_article', related_query_name='published_article')
    pub_time = models.DateTimeField(auto_now=True, editable=False)
    url = models.URLField()

    class Meta:
        app_label = 'backstage'
        db_table = 'published_articles'
        verbose_name = '已发布的文章'


class Article(models.Model):
    ARTICLE_TYPES = {
        ('original', '原创'),
        ('reprint', '转载'),
        ('translation', '翻译')
    }

    STATUS_TYPE = {
        (0, 'DELETED'),
        (1, 'IN DRAFTS'),
        (2, 'PUBLISHED')
    }

    article_id = models.AutoField(primary_key=True, unique=True)
    title = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=ARTICLE_TYPES, default='original')
    created_time = models.DateTimeField(auto_now=True, editable=False)
    latest_modify_time = models.DateTimeField(auto_now=True)
    status = models.SmallIntegerField(choices=STATUS_TYPE, default=1)
    html_file_path = models.URLField(default="/")
    md_file_path = models.URLField(default="/")

    def __str__(self):

        return "[" + \
               str(self.article_id) + ", " + \
               self.title + ", " + \
               self.type + ", " + \
               str(self.status) + "]"

    class Meta:
        app_label = 'backstage'
        db_table = 'articles'
        verbose_name = '所有文章'


class Category(models.Model):

    category_name = models.CharField(max_length=50)
    category_describe = models.TextField(null=True)
    created_time = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        app_label = 'backstage'
        db_table = 'categories'
        verbose_name = '文章的类别'


class Comment(models.Model):

    belonged_pub_article = models.ForeignKey('PublishedArticle', to_field='pub_id', on_delete=models.SET_DEFAULT,
                                             default=None, related_name="comments", related_query_name="comments")
    commentator = models.CharField(max_length=50)
    comment_content = models.TextField()
    comment_time = models.DateTimeField(auto_now=True, editable=False)
    parent_comment = models.ForeignKey('self', on_delete=models.SET_DEFAULT, null=True, related_name="child_comment", default=None)
    reply = models.ForeignKey('self', on_delete=models.SET_DEFAULT, null=True, related_name="reply_to", default=None)

    class Meta:
        app_label = 'backstage'
        db_table = 'comments'
        verbose_name = '文章中的评论'


class Message(models.Model):

    subject = models.CharField(max_length=50)
    writer = models.CharField(max_length=20)
    concat_info = models.CharField(max_length=50)
    message = models.TextField()
    readed = models.BooleanField(default=False)
    compose_time = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        app_label = 'backstage'
        db_table = 'messages'
        verbose_name = '博客留言'

backstage/views/article_view.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import OperationalError, DatabaseError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from backstage.models import Article, PublishedArticle, cancel_publish_in_redis, RedisError


def all_articles(request, page=1):
    context = {}
    try:
        articles = Article.objects.order_by("-created_time")
        paginator = Paginator(articles, 10)
        try:
            articles_in_page = paginator.page(page)
        except PageNotAnInteger:
            articles_in_page = paginator.page(1)
        except EmptyPage:
            articles_in_page = paginator.page(paginator.num_pages)

        context['articles'] = articles_in_page
        context['pages'] = range(1, paginator.num_pages + 1)

    except OperationalError:
        pass
    return render(request, 'backstage/all_articles.html', context)


def published_articles(request, page=1):
    context = {}
    try:
        pub_articles = PublishedArticle.objects.order_by('-pub_time')
        paginator = Paginator(pub_articles, 10)
        try:
            pub_articles_in_page = paginator.page(page)
        except PageNotAnInteger:
            pub_articles_in_page = paginator.page(1)
        except EmptyPage:
            pub_articles_in_page = paginator.page(paginator.num_pages)

        context['pub_articles'] = pub_articles_in_page
        context['pages'] = range(1, paginator.num_pages + 1)

    except OperationalError:
        pass

    return render(request, 'backstage/pub_articles.html', context)


def to_edit(request, article_id):
    request.session['article_id'] = article_id
    return redirect('backstage:edit_article', new='edited')


def to_delete(request):
    if request.is_ajax() and request.method == 'POST':
        delete_articles = request.POST.getlist('delete_articles', default=[])
        try:
            articles = Article.objects.in_bulk(delete_articles)
            for delete_id in articles:
                if articles[delete_id].status != 2:
                    articles[delete_id].status = 0
                    articles[delete_id].save()
        except:
            return HttpResponse("删除失败！", status=403)
        return HttpResponse('删除成功')

    return HttpResponse(status=404)


def cancel_publish(request):

    if request.is_ajax() and request.method == 'POST':
        cancel_publish_articles = request.POST.getlist('delete_articles', default=[])
        print("从网页接收的要取消发布的文章的 primary key 列表 ->", cancel_publish_articles)
        try:
            pub_articles = PublishedArticle.objects.in_bulk(cancel_publish_articles)
            print("要取消发布的文章列表 -> ", pub_articles)
            for key in pub_articles:
                print("要取消发布的文章 -> ", pub_articles[key])
                cancel_publish_in_redis(pub_articles[key].pub_id)
                pub_articles[key].article.status = 1
                pub_articles[key].article.save()
                pub_articles[key].delete()

        except (DatabaseError, RedisError):
            return HttpResponse("取消发布失败！", status=403)
        return HttpResponse('取消发布成功')

    return HttpResponse(status=404)

backstage/views/category_view.py
from django.db import OperationalError
from django.http import Http404
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from backstage.models import Category

CONTEXT_FOR_CATEGORY = {}


def category(request, page=1):
    try:
        categories = Category.objects.order_by("-created_time")
        paginator = Paginator(categories, 10)
        try:
            categories_in_page = paginator.page(page)
        except PageNotAnInteger:
            categories_in_page = paginator.page(1)
        except EmptyPage:
            categories_in_page = paginator.page(paginator.num_pages)

        CONTEXT_FOR_CATEGORY['categories'] = categories_in_page
        CONTEXT_FOR_CATEGORY['pages'] = range(1, paginator.num_pages + 1)
        return render(request, 'backstage/category.html', CONTEXT_FOR_CATEGORY)
    except OperationalError:
        raise Http404
    finally:
        CONTEXT_FOR_CATEGORY.clear()


def create_category(request):

    if request.method == "POST":
        category_name = request.POST['name']
        category_describe = request.POST['details']
        new_category = Category(category_name=category_name, category_describe=category_describe)

        try:
            new_category.save()
            CONTEXT_FOR_CATEGORY['result'] = 'OK!创建成功！'
        except OperationalError:
            CONTEXT_FOR_CATEGORY['result'] = '创建成功！'
        return redirect('backstage:category')
    else:
        raise Http404('Page Not Found!')


def delete_category(request, category_id):

    try:
        c = Category.objects.get(id=category_id)
        c.delete()
        CONTEXT_FOR_CATEGORY['result'] = "OK!删除成功！"
    except:
        CONTEXT_FOR_CATEGORY['result'] = "删除失败！"
    return redirect('backstage:category')

backstage/views/draft_trash_view.py
from django.db import OperationalError, DatabaseError
import os
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render

from backstage.models import Article


def draft_and_trash(request, dt='draft', p=1):
    context = {}
    try:

        status = 1
        template = 'backstage/draft.html'
        if dt == "trash":
            status = 0
            template = 'backstage/trash.html'

        articles = Article.objects.filter(status=status).order_by("-created_time")
        paginator = Paginator(articles, 10)
        try:
            articles_in_page = paginator.page(p)
        except PageNotAnInteger:
            articles_in_page = paginator.page(1)
        except EmptyPage:
            articles_in_page = paginator.page(paginator.num_pages)

        context['articles'] = articles_in_page
        context['pages'] = range(1, paginator.num_pages + 1)
        return render(request, template, context)

    except OperationalError:
        return render(request, 'errorpages/404.html')


def delete_permanently(request):

    if request.is_ajax() and request.method == 'POST':
        delete_articles = request.POST.getlist('delete_articles', default=[])
        try:
            articles = Article.objects.in_bulk(delete_articles)
            for delete_id in articles:
                os.remove(articles[delete_id].html_file_path)
                os.remove(articles[delete_id].md_file_path)
                articles[delete_id].delete()
        except:
            return HttpResponse("删除失败！", status=403)
        return HttpResponse('删除成功')

    return HttpResponse(status=404)


def revert_from_trash(request):

    if request.is_ajax() and request.method == 'POST':
        revert_articles = request.POST.getlist('revert_articles', default=[])
        try:
            articles = Article.objects.in_bulk(revert_articles)
            for key in articles:
                if articles[key].status == 0:
                    articles[key].status = 1
                    articles[key].save()
        except DatabaseError:
            return HttpResponse("还原失败！", status=403)
        return HttpResponse('还原成功！')

    return HttpResponse(status=404)

backstage/views/log_view.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from backstage.models import Manager
from backstage.forms import ManagerLoginForm


# Create your views here.


def login(request):
    return render(request, "backstage/login.html", {'manager_login_form': ManagerLoginForm()})


def login_validate(request):
    content = {
        "manager_login_form": ManagerLoginForm(),
        "message": "",
    }

    if request.method == 'POST':

        login_form = ManagerLoginForm(request.POST)
        content['manager_login_form'] = login_form

        if login_form.is_valid():
            login_email = login_form.cleaned_data['email']
            login_password = login_form.cleaned_data['password']
            is_remember = request.POST.get('remember')

            try:
                manager = Manager.objects.get(email=login_email)

                if login_password == manager.password:
                    request.session['admin'] = {'name': manager.name, 'level': manager.level}
                    print(request.session['admin'])
                    # 如果登录时勾选了记住账户，则设置session存活时间为５天，　否则默认为6个小时
                    if is_remember == 'on':
                        request.session.set_expiry(432000)
                    else:
                        request.session.set_expiry(21600)

                    return redirect('backstage:index')
                else:
                    content['message'] = "密码错误"
                    return render(request, "backstage/login.html", content)
            except Manager.DoesNotExist:
                content['message'] = "用户不存在"
                return render(request, "backstage/login.html", content)
    return render(request, "backstage/login.html", content)


def logout(request):
    request.session.flush()
    return redirect('backstage:login')

templates/backstage/generic.html
{% load staticfiles %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}ONE Blog{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/skins/skin-blue.min.css' %}">
    <link href="/static/favicon-16x16.ico" rel="bookmark" type="image/x-icon" />
    <link href="/static/favicon-32x32.ico" rel="icon" type="image/x-icon" />
    <link href="/static/favicon-16x16.ico" rel="shortcut icon" type="image/x-icon" />
    {% block additionalCss %}{% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <!-- Main Header -->
    <header class="main-header">
        <!-- Logo -->
        <a href="{% url 'blog:blog_index' %}" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>F</b>AN</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>FAN</b>Blog</span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->
                    <li id="messages-menu" class="dropdown messages-menu">
                        <!-- Menu toggle button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-envelope-o"></i>
                            <span class="label label-success"></span>
                        </a>
                        <ul class="dropdown-menu">

                        </ul>
                    </li>
                    <!-- /.messages-menu -->

                    <li id="tasks-menu" class="dropdown tasks-menu">
                        <!-- Menu Toggle Button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-flag-o"></i>
                            <span class="label label-danger">9</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li style="font-size: 1px" class="header"></li>
                            <li class="body">
                                <!-- Inner menu: contains the tasks -->
                                <ul class="menu" style="font-size: 1px">
                                    <li><!-- Task item -->
                                        <a href="{% url 'backstage:all_articles' %}">
                                            <!-- Task title and progress text -->
                                            <h6>
                                                已完成文章比例
                                                <small class="pull-right">100%</small>
                                            </h6>
                                            <!-- The progress bar -->
                                            <div class="progress xs">
                                                <!-- Change the css width attribute to simulate progress -->
                                                <div id="tasks-progress" class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                                                     aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
                                                    <span class="sr-only">100% Complete</span>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <!-- end task item -->
                                </ul>
                            </li>
                            <li class="footer">
                                <a href="{% url 'backstage:draft_and_trash' dt='draft' p=1 %}">去完成&raquo;</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span id="administrator" class="fa fa-user"></span>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li role="presentation">
                                <a role="menuitem" href="#">用户设置</a>
                            </li>
                            <li role="presentation" class="divider"></li>
                            <li role="presentation">
                                <a role="menuitem" href="{% url 'backstage:logout' %}">退出</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

            <!-- Sidebar user panel (optional) -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img id="admin-sidebar-img" src="/static/dist/img/user-default.jpg" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p id="admin-sidebar"></p>
                    <a href="#"><i class="fa fa-circle text-success"></i>在线</a>
                </div>
            </div>

            <!-- search form (Optional) -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
                </div>
            </form>
            <!-- /.search form -->

            <!-- Sidebar Menu -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">导航栏</li>
                <!-- Optionally, you can add icons to the links -->
                <li><a href="{% url 'backstage:statistics' %}"><i class="fa fa-bar-chart"></i> <span>信息统计</span></a>
                <li><a href="{% url 'backstage:edit_article' new='new' %}"><i class="fa fa-pencil-square-o"></i> <span>写博客</span></a></li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-file-text"></i>
                        <span>文章管理</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'backstage:published_articles' %}">已发布文章</a></li>
                        <li><a href="{% url 'backstage:all_articles' %}">所有文章</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'backstage:category' %}"><i class="fa fa-th"></i> <span>分类管理</span></a></li>
                <li>
                    <a href="{% url 'backstage:draft_and_trash' dt='draft' p=1 %}">
                        <i class="fa fa-file-text-o"></i>
                        <span>草稿箱</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'backstage:message_box'%}">
                        <i class="fa fa-inbox"></i>
                        <span>留言箱</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'backstage:draft_and_trash' dt='trash' p=1 %}">
                        <i class="fa fa-trash"></i>
                        <span>回收站</span>
                    </a>
                </li>
                <li><a href="#"><i class="fa fa-cog"></i><span>个人中心</span></a></li>
            </ul>
            <!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        {% block content %}

        {% endblock %}
    </div>
    <!-- /.content-wrapper -->
    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- Default to the left -->
        <strong>Copyright &copy; 2018 <a href="#">Evan.Xu</a>.</strong> All rights reserved.
    </footer>
    <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'bower_components/fastclick/lib/fastclick.js'%}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js'%}"></script>
<script src="{% static 'dist/js/demo.js'%}"></script>
<script src="{% static 'dist/js/navbar.js' %}"></script>
{% block additionalScript %}{% endblock %}
</body>
</html>

templates/backstage/read-message.html
{% extends 'backstage/generic.html' %}
{% load staticfiles %}
{% load humanize %}
{% block title %}{{ message.writer }}的留言-FAN Blog{% endblock %}

{% block additionalCss %}
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'bower_components/iCheck/flat/blue.css' %}">
{% endblock %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            查看留言
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'backstage:message_box' %}"><i class="fa fa-angle-double-right"></i>留言箱</a></li>
        </ol>
    </section>

    <section class="content container-fluid">
		<div class="row">
			<div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">

                        <a href="#" class="btn btn-box-tool btn-sm pull-left" data-toggle="tooltip" title="上一条"><i class="fa fa-chevron-left"></i></a>
                        <a href="#" class="btn btn-box-tool btn-sm pull-right" data-toggle="tooltip" title="下一条"><i class="fa fa-chevron-right"></i></a>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body no-padding">
                        <div class="mailbox-read-info">
                            <h3>{{ message.subject }}</h3>
                            <h5>From: {{ message.concat_info }}
                            <span class="mailbox-read-time pull-right">{{ message.compose_time }}</span></h5>
                        </div>
                        <!-- /.mailbox-read-info -->

                        <div class="mailbox-read-message">
                            {% for m in msg_content %}
                            <p>{{ m }}</p>
                            {% endfor %}
                        </div>
                      <!-- /.mailbox-read-message -->
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /. box -->
            </div>
        </div>
    </section>

{% endblock %}