backstage/urls.py

from django.urls import path, include, re_path

from backstage import views

app_name = 'backstage'

category_patterns = [
    path('', views.category, name="category"),
    path('page/<int:page>/', views.category, name="category_pages"),
    path('create/', views.create_category, name="create_new_category"),
    path('delete/<int:category_id>/', views.delete_category, name="delete_category"),
]

edit_patterns = [
    path('', views.edit_article, name="edit"),
    re_path("(?P<new>(new|edited))/", views.edit_article, name="edit_article"),
    path('save/', views.save_article, name="save_article"),
    path('publish/', views.pub_article, name="publish_article"),
    path('load/', views.load_markdown, name="load_markdown"),
    path('full-editor/', views.edit_article, kwargs={'is_full': True}, name="full_editor")
]

articles_patterns = [
    path('all/', views.all_articles, name="all_articles"),
    path('all/page/<int:page>/', views.all_articles, name="all_articles_pages"),
    path('all/e/<int:article_id>/', views.to_edit, name="to_edit_from_all"),
    path('all/d/', views.to_delete, name="to_delete_from_all"),
    path('published/', views.published_articles, name="published_articles"),
    path('published/page/<int:page>/', views.published_articles, name="pub_articles_pages"),
    path('published/e/<int:article_id>/', views.to_edit, name="to_edit_from_pub"),
    path('published/d/', views.cancel_publish, name="to_delete_from_pub"),
    path('revert/', views.revert_from_trash, name="revert_from_trash"),
    path('delPermanently/', views.delete_permanently, name="delete_permanently"),
]

statistics_patterns = [
    path('', views.statistics, name="statistics"),
    path('sys/', views.sys, name="get_system_info"),
    path('nav/', views.nav_info, name="get_nav_info"),
    path('location/', views.get_visitors_location_info, name='get_location_info'),
    path('pv/<int:option>/', views.get_pv_info, name="get_pv_info")
]

upload_patterns = [
    path('image/', views.image_upload, name="image_upload"),
]

message_box_patterns = [
    path('', views.message_box, name="message_box"),
    path('p/<int:p>/', views.message_box, name="message_pages"),
    path('read/<int:message_id>/', views.read_message, name="read_message"),
    path('delete/', views.delete_message, name="delete_message"),
    path('stat/', views.change_stat, name="change_state"),
]

urlpatterns = [
    path('', views.statistics, name="index"),
    path('login/', views.login, name='login'),
    path('login_validate/', views.login_validate, name='validate'),
    path('logout/', views.logout, name='logout'),
    path('statistics/', include(statistics_patterns)),
    path('category/', include(category_patterns)),
    path('edit/', include(edit_patterns)),
    path('articles/', include(articles_patterns)),
    re_path("(?P<dt>(draft|trash))/(?P<p>\d*)/", views.draft_and_trash, name="draft_and_trash"),
    path('upload/', include(upload_patterns)),
    path('message/', include(message_box_patterns))
]


blog/urls.py
from django.urls import path, include
from blog import views

app_name = 'blog'

details_patterns = [
    path('<int:p>/', views.get_all_puba, name="get_all_published_articles"),
    path('details/<int:pub_id>', views.get_detail, name="published_article_detail"),
    path('praise/', views.praise, name="praise"),
    path('comment/', views.to_comment, name="comment"),
    path('load_comments/', views.load_comments, name="load_comments")
]

side_info_patterns = [
    path('latest/', views.get_latest_articles, name="get_latest_articles"),
    path('popular/', views.get_popular_articles, name="get_popular_articles"),
    path('categories/', views.get_categories, name="get_categories")
]

categories_patterns = [
    path('<int:c>/', views.category_view, name="category_view"),
    path('<int:c>/p/<int:p>/', views.category_view, name="category_view_pages")
]

message_patterns = [
    path('', views.message, name="leaving message"),
    path('compose/', views.compose, name="compose message")
]

urlpatterns = [
    path('', views.get_all_puba, name="blog_index", kwargs={'p': 1}),
    path('a/', include(details_patterns)),
    path('side/', include(side_info_patterns)),
    path('categories/', include(categories_patterns)),
    path('message/', include(message_patterns))
]

ip/urls.py
from django.urls import path
from ip import views


app_name = 'ip'

urlpatterns = [
    path('', views.ip_query, name='ip_query'),
    path('query/', views.do_ip_query, name='do_ip_query'),
]

one/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='blog/')),
    path('back/', include('backstage.urls')),
    path('captcha/', include('captcha.urls')),
    path('blog/', include('blog.urls')),
    path('ip/', include('ip.urls')),
    path('favicon.ico', RedirectView.as_view(url='static/favicon.ico'))
]

handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.page_error

backstage/models/article_models.py
from django.db import models


class PublishedArticle(models.Model):

    pub_id = models.IntegerField(unique=True)
    article = models.OneToOneField('Article', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.SET_DEFAULT, default=1,
                                 related_name='published_article', related_query_name='published_article')
    pub_time = models.DateTimeField(auto_now=True, editable=False)
    url = models.URLField()

    class Meta:
        app_label = 'backstage'
        db_table = 'published_articles'
        verbose_name = '已发布的文章'


class Article(models.Model):
    ARTICLE_TYPES = {
        ('original', '原创'),
        ('reprint', '转载'),
        ('translation', '翻译')
    }

    STATUS_TYPE = {
        (0, 'DELETED'),
        (1, 'IN DRAFTS'),
        (2, 'PUBLISHED')
    }

    article_id = models.AutoField(primary_key=True, unique=True)
    title = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=ARTICLE_TYPES, default='original')
    created_time = models.DateTimeField(auto_now=True, editable=False)
    latest_modify_time = models.DateTimeField(auto_now=True)
    status = models.SmallIntegerField(choices=STATUS_TYPE, default=1)
    html_file_path = models.URLField(default="/")
    md_file_path = models.URLField(default="/")

    def __str__(self):

        return "[" + \
               str(self.article_id) + ", " + \
               self.title + ", " + \
               self.type + ", " + \
               str(self.status) + "]"

    class Meta:
        app_label = 'backstage'
        db_table = 'articles'
        verbose_name = '所有文章'


class Category(models.Model):

    category_name = models.CharField(max_length=50)
    category_describe = models.TextField(null=True)
    created_time = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        app_label = 'backstage'
        db_table = 'categories'
        verbose_name = '文章的类别'


class Comment(models.Model):

    belonged_pub_article = models.ForeignKey('PublishedArticle', to_field='pub_id', on_delete=models.SET_DEFAULT,
                                             default=None, related_name="comments", related_query_name="comments")
    commentator = models.CharField(max_length=50)
    comment_content = models.TextField()
    comment_time = models.DateTimeField(auto_now=True, editable=False)
    parent_comment = models.ForeignKey('self', on_delete=models.SET_DEFAULT, null=True, related_name="child_comment", default=None)
    reply = models.ForeignKey('self', on_delete=models.SET_DEFAULT, null=True, related_name="reply_to", default=None)

    class Meta:
        app_label = 'backstage'
        db_table = 'comments'
        verbose_name = '文章中的评论'


class Message(models.Model):

    subject = models.CharField(max_length=50)
    writer = models.CharField(max_length=20)
    concat_info = models.CharField(max_length=50)
    message = models.TextField()
    readed = models.BooleanField(default=False)
    compose_time = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        app_label = 'backstage'
        db_table = 'messages'
        verbose_name = '博客留言'

blog/models.py
from django.db import models

# Create your models here.

import redis

CONNECTION_POOL_BLOG = redis.ConnectionPool(host='localhost', port=6379)
CONNECTION_BLOG = redis.Redis(connection_pool=CONNECTION_POOL_BLOG)


def get_redis_connection():

    return CONNECTION_BLOG

blog/views/all_pub_view.py
from django.shortcuts import render
from redis import RedisError

from backstage.models import get_redis_connection, hgetall_pub_article


def get_all_puba(request, p=1):

    if p <= 0:
        p = 1

    num_per_page = 10
    start = (p - 1) * num_per_page
    end = p * num_per_page - 1
    try:
        conn = get_redis_connection()
        total_pages = int(conn.llen('all_pub_articles:') / num_per_page) + 1
        puba_list = conn.lrange('all_pub_articles:', start=start, end=end)
        results = []
        for item in puba_list:
            puba_name = item.decode("utf-8")
            puba = hgetall_pub_article(puba_name)
            results.append(puba)

        context = {
            'all_pubas': results,
            'total_pages': range(1, total_pages + 1),
            'current_page': p
        }
    except RedisError:
        context = {}
    return render(request, 'blog/all.html', context)


# def get_all_puba_from_sql(p=1):
#     context = {}
#     try:
#         pub_articles = PublishedArticle.objects.order_by('-pub_time')
#         paginator = Paginator(pub_articles, 10)
#         try:
#             pub_articles_in_page = paginator.page(page)
#         except PageNotAnInteger:
#             pub_articles_in_page = paginator.page(1)
#         except EmptyPage:
#             pub_articles_in_page = paginator.page(paginator.num_pages)
#
#         context['pub_articles'] = pub_articles_in_page
#         context['pages'] = range(1, paginator.num_pages + 1)
#
#     except OperationalError:
#         pass

blog/views/category_view.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import OperationalError
from django.shortcuts import render

from backstage.models import Category


def category_view(request, c, p=1):

    context = {}
    try:
        category = Category.objects.get(pk=c)
        category_name = category.category_name
        context['category_id'] = c
        context['category_name'] = category_name

        articles = category.published_article.all().order_by('-pub_time')
        paginator = Paginator(articles, 10)
        try:
            pub_articles_in_page = paginator.page(p)
        except PageNotAnInteger:
            pub_articles_in_page = paginator.page(1)
        except EmptyPage:
            pub_articles_in_page = paginator.page(paginator.num_pages)

        context['pub_articles'] = pub_articles_in_page
        context['pages'] = range(1, paginator.num_pages + 1)
    except OperationalError:
        pass

    return render(request, 'blog/categories.html', context)

blog/views/details_view.py
import json

from django.core.exceptions import ObjectDoesNotExist
from django.db import DatabaseError
from django.http import HttpResponse
from django.shortcuts import render
from redis import RedisError
import time
from backstage.models import PublishedArticle, hgetall_pub_article, article_vote, article_visit_record, has_voted, \
    Comment, comment_record_in_redis
import os


def get_detail(request, pub_id):

    try:
        published_article = PublishedArticle.objects.get(pub_id=pub_id)
        title = published_article.article.title
        article_type = published_article.article.get_type_display()
        category = published_article.category.category_name
        pub_time = published_article.pub_time
        html_file_path = published_article.article.html_file_path
        total_comments_number = Comment.objects.filter(belonged_pub_article_id=pub_id).count()

        if os.path.exists(html_file_path):
            html_file_path = html_file_path.split("/")[-1]
        else:
            return render(request, 'errorpages/404.html')
    except DatabaseError:
        return render(request, 'errorpages/404.html')

    username = request.session.get('username', "")

    ip = request.get_host()
    if ip.find(":"):
        ip = ip.partition(":")[0]

    if username:
        visit_record = "user:" + username
    else:
        visit_record = "visitor:" + ip

    voted = has_voted(visit_record, pub_id)

    try:
        article_visit_record(visit_record, pub_id)
        puba_in_redis = hgetall_pub_article('pub_article:' + str(pub_id))
        votes = puba_in_redis['votes']
        visitors = puba_in_redis['visitor']
    except RedisError:
        votes = 0
        visitors = 0

    context = {
        'pub_id': pub_id,
        'title': title,
        'type': article_type,
        'category': category,
        'pub_time': pub_time,
        'votes': votes,
        'visitors': visitors,
        'html_file_path': html_file_path,
        'is_voted': voted,
        'username': username,
        'total_comments_number': total_comments_number
    }

    try:
        previous_article = published_article.get_previous_by_pub_time()
        context['previous'] = previous_article
    except ObjectDoesNotExist:
        pass
    try:
        next_article = published_article.get_next_by_pub_time()
        context['next'] = next_article
    except ObjectDoesNotExist:
        pass

    return render(request, 'blog/details.html', context)


def praise(request):

    if request.is_ajax():
        pub_id = request.GET.get('pub_id')
        username = request.session.get('username', "")

        ip = request.get_host()
        if ip.find(":"):
            ip = ip.partition(":")[0]

        if username:
            voter = "user:" + username
        else:
            voter = "visitor:" + ip

        praise_result = article_vote(voter, pub_id)

        return HttpResponse(praise_result)

    return render(request, "errorpages/403.html")


def to_comment(request):

    if request.is_ajax() and request.method == "POST":
        username = request.session.get("username", "")
        commentator = "evan"
        pub_id = request.POST.get('pub_id')
        comment_content = request.POST.get('comment')
        comment_content = comment_content.strip()
        comment_id_reply = request.POST.get('commentIdReply')
        child_comment_id_reply = request.POST.get('childCommentIdReply')

        print(comment_id_reply, child_comment_id_reply)

        try:
            comment = Comment(belonged_pub_article_id=pub_id, commentator=commentator, comment_content=comment_content,
                              parent_comment_id=comment_id_reply, reply_id=child_comment_id_reply)
            comment.save()
            comment_record_in_redis(pub_id)
            result = "评论成功！"
        except DatabaseError:
            result = "评论失败，无法连接数据库！"

        return HttpResponse(result)


def load_comments(request):

    if request.is_ajax():
        pub_id = request.GET.get('pub_id')
        comments = Comment.objects.filter(belonged_pub_article_id=pub_id, parent_comment=None).order_by('-comment_time')
        comments_json = comments_to_json(comments)
        print(comments_json)
        return HttpResponse(json.dumps(comments_json), content_type='json')


def comments_to_json(comments):
    comments_json = []

    for comment in comments:
        comment_json = comment_to_json(comment)
        child_comments = comment.child_comment.all().order_by('comment_time')
        if child_comments.count() > 0:
            child_comments_json = comments_to_json(child_comments)
            comment_json['childComments'] = child_comments_json
        comments_json.append(comment_json)

    return comments_json


def comment_to_json(comment):

    comment_json = dict()
    comment_json['commentId'] = str(comment.id)
    comment_json['commentator'] = comment.commentator
    comment_json['commentTime'] = comment.comment_time.strftime("%Y-%m-%d %H:%M:%S")
    comment_json['commentContent'] = comment.comment_content
    if comment.reply:
        comment_json['replyTo'] = comment.reply.commentator
    return comment_json


def to_reply(request):
    pass

blog/views/message_view.py
from django.db import DatabaseError
from django.http import HttpResponse, Http404
from django.shortcuts import render

from backstage.models import Message


def message(request):
    return render(request, 'blog/message.html')


def compose(request):

    if request.is_ajax() and request.method == 'POST':
        subject = request.POST.get('subject')
        writer = request.POST.get('writer')
        concat_info = request.POST.get('concat_info')
        message_content = request.POST.get('message')
        try:
            msg = Message(subject=subject, writer=writer, concat_info=concat_info, message=message_content)
            msg.save()
        except DatabaseError:
            return HttpResponse('数据库错误！留言失败！', content_type='text')

        return HttpResponse('提交成功！', content_type='text')

    return Http404

templates/blog/basic.html
{% load staticfiles %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}FAN Blog{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'dist/css/skins/skin-blue.min.css' %}">
    <link rel="stylesheet" href="{% static 'editor-md/css/editormd.css' %}">
    <link href="/static/favicon-16x16.ico" rel="bookmark" type="image/x-icon" />
    <link href="/static/favicon-32x32.ico" rel="icon" type="image/x-icon" />
    <link href="/static/favicon-16x16.ico" rel="shortcut icon" type="image/x-icon" />
    {% block additionalCss %}{% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-black-light layout-top-nav">
<div class="wrapper">

    <header class="main-header">
        <nav class="navbar navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <b class="navbar-brand">FAN</b>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'blog:blog_index' %}">博客<span class="sr-only">(current)</span></a></li>
                        <li class="active"><a href="http://www.521fan.com/fm/">FM</a></li>
                        <li class="active"><a href="{% url 'blog:leaving message' %}">写留言</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">More<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="/ip">IP归属地查询</a></li>
                                <li class="divider"></li>
                                <li><a href="#">More pages coming soon</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
                        </div>
                    </form>
                </div>
                <!-- /.navbar-collapse -->
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li><a href="#" data-toggle="modal" data-target="#loginModal">登录</a></li>
                        <!-- User Account Menu -->
{#                        <li class="dropdown user user-menu">#}
{#                            <!-- Menu Toggle Button -->#}
{##}
{#                            <ul class="dropdown-menu">#}
{#                                <!-- Menu Footer-->#}
{#                                <li class="user-footer">#}
{#                                    <div class="pull-left">#}
{#                                        <a href="#" class="btn btn-default btn-flat">切换账号</a>#}
{#                                    </div>#}
{#                                    <div class="pull-right">#}
{#                                        <a href="#" class="btn btn-default btn-flat">注销</a>#}
{#                                    </div>#}
{#                                </li>#}
{#                            </ul>#}
{#                        </li>#}

                    </ul>
                </div>
                <!-- /.navbar-custom-menu -->
            </div>
            <!-- /.container-fluid -->
        </nav>
    </header>
    <!-- Full Width Column -->
    <div class="content-wrapper">
        <div class="container">
            {% block content_header %}

            {% endblock %}

            <!-- Main content -->
            <section class="content">
                <!--row-->
                <div class="row">
                    <!--col-->
                    <div class="col-md-9" >
                        {% block content_body %}

                        {% endblock %}
                    </div>
                    <!--/.col-->

                    <!--col-->
                    <div class="col-md-3">

                        <!-- Widget: user widget style 1 -->
                        <div class="box box-widget widget-user-2">
                            <!-- Add the bg color to the header using any of the bg-* classes -->
                            <div class="widget-user-header bg-light-blue ">
                                <div class="widget-user-image">
                                    <img class="img-circle" src="{% static 'dist/img/fan.jpg' %}" alt="User Avatar">
                                </div>
                                <!-- /.widget-user-image -->
                                <h3 class="widget-user-username">Evan Xu</h3>
                                <h5 class="widget-user-desc">Rookie Coder</h5>
                            </div>
                            <div class="box-footer no-padding text-bold">
                                <ul class="nav nav-stacked">
                                    <li><a href="http://blog.csdn.net/github_39376455"><span class="fa fa-file-text">&nbsp;</span>CSDN</a></li>
                                    <li><a href="https://github.com/1EvanXu/"><span class="fa fa-github">&nbsp;</span>GitHub</a></li>
                                    <li><a href="#"><span class="fa fa-envelope-o">&nbsp;</span>Email<small class="pull-right">yifan_xu6@163.com</small></a></li>
                                    <li><a href="#"><span class="fa fa-map-marker">&nbsp;</span>Nanjing</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- /.widget-user -->

                        <div id="latest-articles-box" class="box box-solid">
                            <div class="box-header with-border">
                                <h3 class="box-title">最新文章</h3>
                                <span class="pull-right text-info">
                                    <a href="/blog/a/1/">更多文章</a>
                                </span>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body" style="color: gray">
                                <ul class="list-unstyled">

                                </ul>
                            </div>
                            <!-- /.box-body -->
                            <div class="overlay">
                                <i class='fa fa-refresh fa-spin'></i>
                            </div>
                        </div>
                        <!-- /.box -->

                        <div id="popular-articles-box" class="box box-solid">
                            <div class="box-header with-border">
                                <h3 class="box-title">最热文章</h3>
                                <span class="pull-right text-info">热度</span>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body" style="color: gray">
                                <ul class="list-unstyled">

                                </ul>
                            </div>
                            <!-- /.box-body -->
                            <div class="overlay">
                                <i class='fa fa-refresh fa-spin'></i>
                            </div>
                        </div>
                        <!-- /.box -->

                        <div id="category-box" class="box box-solid">
                            <div class="box-header with-border">
                                <h3 class="box-title">文章分类</h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body" style="color: gray">
                                <ul class="list-unstyled">

                                </ul>
                            </div>
                            <!-- /.box-body -->
                            <div class="overlay">
                                <i class='fa fa-refresh fa-spin'></i>
                            </div>
                        </div>
                        <!-- /.box -->
                    </div>
                    <!--/.col-->
                </div>
                <!--/.row-->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.container -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">

        <!-- Default to the left -->
        <strong>Copyright
            <a href="{% url 'backstage:index' %}">&copy;</a>
            2018
            <a href="https://weibo.com/u/3014543753">Evan.Xu</a>
            .
        </strong> All rights reserved.
        <strong>Powered by&nbsp;&nbsp;</strong>
        <a href="https://www.djangoproject.com/">
            <img src="/static/dist/img/django-ico.png" width="16" height="16" class="img-circle">
            &nbsp;Django</a>&nbsp;and&nbsp;
        <a href="https://adminlte.io/">
            <img src="/static/dist/img/adminlite-ico.png" width="16" height="16" class="img-circle">
            &nbsp;AdminLite
        </a>
    </footer>
</div>
<!-- ./wrapper -->

{#<!--loginModal-->#}
{#<div class="modal fade" id="loginModal" tabindex="-1" role="dialog"#}
{#   aria-labelledby="loginModalLabel" aria-hidden="true">#}
{#    <div class="modal-dialog">#}
{#        <div class="modal-content">#}
{#            <!--#}
{#            <div class="modal-header">#}
{#                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">#}
{#                    &times;#}
{#                </button>#}
{#                <h4 class="modal-title" id="loginModalLabel">#}
{#                    登录#}
{#                </h4>#}
{#            </div>#}
{#            <div class="modal-body">#}
{#                在这里添加一些文本#}
{#            </div>#}
{#            <div class="modal-footer">#}
{#            </div>#}
{#            -->#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{#<!--./loginModal-->#}

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'bower_components/fastclick/lib/fastclick.js'%}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js'%}"></script>
<script src="{% static 'dist/js/demo.js'%}"></script>
<script src="{% static 'dist/js/sideInfo.js'%}"></script>
{% block additionalScript %}{% endblock %}
</body>
</html>

templates/blog/categories.html
{% extends 'blog/basic.html' %}
{% load staticfiles %}
{% block title %}文章分类-FAN Blog{% endblock %}
{% block content_header %}
<!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            {{ category_name }}
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'blog:blog_index' %}"><i class="fa fa-home"></i> Home</a></li>
        </ol>
    </section>
{% endblock %}


{% block content_body %}
    {% for puba in pub_articles %}
    <div class="box box-solid">
        <div class="box-header">
            <h3>{{ puba.article.title }}</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body text-gray">
            <a href="{{ puba.url }}">阅读全文<i class="fa fa-angle-double-right"></i></a>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <table width="70%" style="color: gray">
                <tr>
                    <td width="10%"><span class="badge">{{ puba.article.get_type_display }}</span></td>
                    <td width="50%"><span class="fa fa-clock-o">&nbsp;</span>{{ puba.pub_time }}</td>
                </tr>
            </table>
        </div>
    </div>
    <!-- /.box -->
    {% endfor %}

    <div class="text-center">

        <ul class="pagination pagination-sm no-margin pull-right">
            <li>
                {% if pub_articles.has_previous %}
                    <a href="{% url 'blog:category_view_pages' c=category_id p=pub_articles.previous_page_number %}">&laquo;</a>
                {% else %}
                    <a href="#">&laquo;</a>
                {% endif %}
            </li>
            {% for page in pages %}
                {% if page == pub_articles.number %}
                    <li><a class="active" href="#">{{ page }}</a></li>
                {% else %}
                    <li><a href="{% url 'blog:category_view_pages' c=category_id p=page %}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}
            <li>
                {% if pub_articles.has_next %}
                    <a href="{% url 'blog:category_view_pages' c=category_id p=articles.next_page_number %}">&raquo;</a>
                {% else %}
                    <a href="#">&raquo;</a>
                {% endif %}
            </li>
        </ul>

    </div>
{% endblock %}